package dialog;

import controller.LoginController;
import helper.MD5Convert;
import java.util.Random;
import javax.swing.JOptionPane;

public class getPass extends javax.swing.JDialog {

    /**
     * Creates new form getPass
     */
    private String code2; 
    private String email ;
    
    public getPass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCoverDialog1 = new component.PanelCoverDialog();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtEmail = new swing.TextInput();
        jLabel1 = new javax.swing.JLabel();
        btnGui = new swing.PhongButton();
        btnCheck = new swing.PhongButton();
        jLabel2 = new javax.swing.JLabel();
        txtXacNhanCode = new swing.TextInput();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new swing.PhongButton();
        txtPass = new swing.MyPasswordField();
        txtRepass = new swing.MyPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐỔI MẬT KHẨU");
        panelCoverDialog1.add(jLabel5);
        jLabel5.setBounds(4, 10, 350, 30);
        panelCoverDialog1.add(jSeparator1);
        jSeparator1.setBounds(10, 50, 400, 10);

        txtEmail.setText(" ");
        panelCoverDialog1.add(txtEmail);
        txtEmail.setBounds(100, 80, 160, 35);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email");
        panelCoverDialog1.add(jLabel1);
        jLabel1.setBounds(20, 80, 40, 40);

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });
        panelCoverDialog1.add(btnGui);
        btnGui.setBounds(270, 80, 80, 35);

        btnCheck.setText("Kiểm tra");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        panelCoverDialog1.add(btnCheck);
        btnCheck.setBounds(270, 150, 80, 35);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Code");
        panelCoverDialog1.add(jLabel2);
        jLabel2.setBounds(20, 150, 40, 30);
        panelCoverDialog1.add(txtXacNhanCode);
        txtXacNhanCode.setBounds(100, 150, 160, 35);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mật khẩu mới");
        panelCoverDialog1.add(jLabel3);
        jLabel3.setBounds(10, 230, 80, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nhập lại");
        panelCoverDialog1.add(jLabel4);
        jLabel4.setBounds(20, 290, 50, 30);

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        panelCoverDialog1.add(btnXacNhan);
        btnXacNhan.setBounds(270, 260, 80, 35);

        txtPass.setText("Password11");
        panelCoverDialog1.add(txtPass);
        txtPass.setBounds(100, 230, 160, 35);

        txtRepass.setText("myPassword");
        panelCoverDialog1.add(txtRepass);
        txtRepass.setBounds(100, 290, 160, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoverDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoverDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        txtEmail.getText();
        String abc = generateRandomString();
        loginController.resetVerifycode(txtEmail.getText(), abc);
        Object[] info = new Object[3];
        info[0]=txtEmail.getText();
        info[1]="ResetPass";
        info[2]=abc;
        email = txtEmail.getText();
        loginController.sendMail(info);
        JOptionPane.showMessageDialog(this, "Gửi thành công vui lòng kiểm tra email!");
        txtXacNhanCode.setEnabled(true);
        btnCheck.setEnabled(true);
        code2=loginController.getVerifycode(txtEmail.getText());
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        String code=txtXacNhanCode.getText();
        if(code.equals(code2)){
            txtPass.setEnabled(true);
            txtRepass.setEnabled(true);
            btnXacNhan.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "Sai mã xác nhận vui lòng nhập lại!");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String pass = new String(txtPass.getPassword());
        String RePass = new String(txtRepass.getPassword());
        
        if(!pass.equals(RePass)){
            JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp");
        }else{
            pass=MD5Convert.getMd5(pass);
            loginController.updatePass(email,pass);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            this.dispose();
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed
    
    LoginController loginController;
    
    public void setController(LoginController loginController){
        this.loginController= loginController;
    }
    
    String CHAR_LIST = "0123456789";
    public String generateRandomString(){
        int RANDOM_STRING_LENGTH = 6;
		 StringBuffer randStr = new StringBuffer();
		 for(int i=0; i<RANDOM_STRING_LENGTH; i++)
	     {
	    	 int number = getRandomNumber();
	    	 char ch = CHAR_LIST.charAt(number);
	    	 randStr.append(ch);
	     }
	     return randStr.toString();
	  }
    
    private int getRandomNumber() 
	 {
		 int randomInt = 0;
	     Random randomGenerator = new Random();
	     randomInt = randomGenerator.nextInt(CHAR_LIST.length());
	     if (randomInt - 1 == -1) 
	     {
	    	 return randomInt;
	     } 
	     else 
	     {
	    	 return randomInt - 1;
	     }
	  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getPass dialog = new getPass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public swing.PhongButton btnCheck;
    public swing.PhongButton btnGui;
    public swing.PhongButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private component.PanelCoverDialog panelCoverDialog1;
    public swing.TextInput txtEmail;
    public swing.MyPasswordField txtPass;
    public swing.MyPasswordField txtRepass;
    public swing.TextInput txtXacNhanCode;
    // End of variables declaration//GEN-END:variables
}
