package dialog;

public class ThanhToan extends javax.swing.JDialog {

    public ThanhToan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelCoverDialog1 = new component.PanelCoverDialog();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTenPhong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonOutLine1 = new swing.ButtonOutLine();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHuy = new swing.PhongButton();
        btnTTKhongIn = new swing.PhongButton();
        btnThanhToanDone = new swing.PhongButton();
        txtTongTien = new swing.TextInput();
        txtKhachDua = new swing.TextInput();
        txtTraLai = new swing.TextInput();

        jButton4.setText("Thanh toán và In");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Thanh Toán");
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THANH TOÁN");
        panelCoverDialog1.add(jLabel6);
        jLabel6.setBounds(0, 0, 480, 30);
        panelCoverDialog1.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 480, 10);

        lblTenPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelCoverDialog1.add(lblTenPhong);
        lblTenPhong.setBounds(80, 40, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PHÒNG : ");
        panelCoverDialog1.add(jLabel7);
        jLabel7.setBounds(10, 40, 70, 17);

        buttonOutLine1.setBackground(new java.awt.Color(255, 0, 51));
        buttonOutLine1.setText("In phiếu tạm tính");
        panelCoverDialog1.add(buttonOutLine1);
        buttonOutLine1.setBounds(335, 40, 120, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tổng tiền: ");
        panelCoverDialog1.add(jLabel3);
        jLabel3.setBounds(70, 90, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Khách đưa:");
        panelCoverDialog1.add(jLabel4);
        jLabel4.setBounds(70, 140, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Trả lại: ");
        panelCoverDialog1.add(jLabel5);
        jLabel5.setBounds(70, 190, 70, 30);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        panelCoverDialog1.add(btnHuy);
        btnHuy.setBounds(320, 300, 140, 40);

        btnTTKhongIn.setText("Thanh toán và không in");
        panelCoverDialog1.add(btnTTKhongIn);
        btnTTKhongIn.setBounds(320, 240, 140, 40);

        btnThanhToanDone.setText("Thanh toán và in");
        panelCoverDialog1.add(btnThanhToanDone);
        btnThanhToanDone.setBounds(170, 240, 140, 40);

        txtTongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongTien.setText("0");
        panelCoverDialog1.add(txtTongTien);
        txtTongTien.setBounds(160, 90, 300, 29);

        txtKhachDua.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKhachDua.setText("0");
        panelCoverDialog1.add(txtKhachDua);
        txtKhachDua.setBounds(160, 140, 300, 29);

        txtTraLai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTraLai.setText("0");
        panelCoverDialog1.add(txtTraLai);
        txtTraLai.setBounds(160, 190, 300, 29);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoverDialog1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCoverDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.PhongButton btnHuy;
    public swing.PhongButton btnTTKhongIn;
    public swing.PhongButton btnThanhToanDone;
    private swing.ButtonOutLine buttonOutLine1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblTenPhong;
    private component.PanelCoverDialog panelCoverDialog1;
    public swing.TextInput txtKhachDua;
    public swing.TextInput txtTongTien;
    public swing.TextInput txtTraLai;
    // End of variables declaration//GEN-END:variables
}
